package marco.demos.pam.mydemopam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RequestData() {
    }




}